In [6]:
import pandas  as pd
import numpy as np
import string

In [7]:
data=pd.read_csv(r"C:\Users\Kala\Desktop\SEM 8 lab\nlp_lab\dataset\archive\IMDB Dataset.csv")
data.head

<bound method NDFrame.head of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>

In [8]:
data.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [9]:
data['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [10]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
features = data['review']

In [12]:
def fn(sequence):
    for i in sequence:
        if i not in string.punctuation:
            i.lower()
            print(i)

In [13]:
features = features.apply(lambda sequence:[ltrs.lower() for ltrs in sequence if ltrs not in string.punctuation ])
features

0        [o, n, e,  , o, f,  , t, h, e,  , o, t, h, e, ...
1        [a,  , w, o, n, d, e, r, f, u, l,  , l, i, t, ...
2        [i,  , t, h, o, u, g, h, t,  , t, h, i, s,  , ...
3        [b, a, s, i, c, a, l, l, y,  , t, h, e, r, e, ...
4        [p, e, t, t, e, r,  , m, a, t, t, e, i, s,  , ...
                               ...                        
49995    [i,  , t, h, o, u, g, h, t,  , t, h, i, s,  , ...
49996    [b, a, d,  , p, l, o, t,  , b, a, d,  , d, i, ...
49997    [i,  , a, m,  , a,  , c, a, t, h, o, l, i, c, ...
49998    [i, m,  , g, o, i, n, g,  , t, o,  , h, a, v, ...
49999    [n, o,  , o, n, e,  , e, x, p, e, c, t, s,  , ...
Name: review, Length: 50000, dtype: object

In [14]:
features = features.apply(lambda wrd: ''.join(wrd))
features[1]

'a wonderful little production br br the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life br br the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [15]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
# Creating a function to perform stemming
def stemming(text):
    s = []
    for words in text.split():
        s.append(ps.stem(words))
    a = s[:]
    s.clear()
    return ' '.join(a)
# Applying that function in review feature to perform stemming
features=features.apply(stemming)
features[2]

'i thought thi wa a wonder way to spend time on a too hot summer weekend sit in the air condit theater and watch a lightheart comedi the plot is simplist but the dialogu is witti and the charact are likabl even the well bread suspect serial killer while some may be disappoint when they realiz thi is not match point 2 risk addict i thought it wa proof that woodi allen is still fulli in control of the style mani of us have grown to lovebr br thi wa the most id laugh at one of woodi comedi in year dare i say a decad while ive never been impress with scarlet johanson in thi she manag to tone down her sexi imag and jump right into a averag but spirit young womanbr br thi may not be the crown jewel of hi career but it wa wittier than devil wear prada and more interest than superman a great comedi to go see with friend'

In [16]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data["sentiment"]=encoder.fit_transform(data["sentiment"])

In [17]:
y = data.iloc[:,-1].values # Dependent Variable
y

array([1, 1, 1, ..., 0, 0, 0])

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000,binary=True)
X = cv.fit_transform(features).toarray() # Independent Variable


In [19]:
len(X[0])

10000

In [20]:
# cv.get_feature_names()

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [22]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB,GaussianNB
from sklearn.metrics import accuracy_score
model1 = MultinomialNB()
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)


In [23]:
print("Model 1 Accuary: ",accuracy_score(y_test,y_pred1))

Model 1 Accuary:  0.851


In [24]:
a=[" bad wrost "]

In [25]:
X_n = cv.transform(a).toarray() # Independent Variable

In [26]:
X_n

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
y_pred2 = model1.predict(X_n)

In [28]:
y_pred2

array([0])

In [29]:
encoder.inverse_transform(y_pred2)[0]

'negative'

In [30]:
# a=["bad wrost "]
# from nltk.stem.porter import PorterStemmer
# ps = PorterStemmer()
# def stemming(text):
#     s = []
#     for words in text.split():
#         s.append(ps.stem(words))
#     a = s[:]
#     s.clear()
#     return ' '.join(a)
# # Applying that function in review feature to perform stemming
# a=a.apply(stemming)


# cv = CountVectorizer(max_features=10000,binary=True)
# X = cv.fit_transform(features).toarray() # Independent Variable